### ISSUE TITLE
Add loading animation to Gallery page

### ISSUE THREAD

**Issue by SharmaMitchell** [SLorant/Snowy-Snaps#4]
It's currently a bit unclear when photos are loading in the gallery (partially due to the long load times as well).  
Suggested fix: Add a loading animation/indicator to the Gallery page for clarity

**Comment by SLorant** [comment]
While the loading animation works, the user doesn't see his own pictures first, but all pictures in the database. This is because in useFirestore a curly bracket is missing from the first check. When I fixed that, the site crashed - the userID was null in the very first render - that's why the first useEffect loading thing was implemented before.
Fix: Bringing back the useEffect loading method, while keeping the new animation and method doesn't intersect, so they work together well, and on the surface it is the same.
